### PR TITLE
sets variable for call out box title

### LINKED ISSUE #410: Colour contrast issue on call out box title
image

The default styling from the base theme has a black header on the purple. Can we change this to white please :)

### PR DESCRIPTION
**Pull request by markconroy**
Closes #410

### CODE REVIEW

**Comment by finnlewis** [comment]
@keelanfh @Adnan-cds @andybroomfield could you check if this would have any unintended or unexpected effect on your sites? 

I think we should be able to release this with details in release notes. 

@msayoung has some more ideas: change the  --call-out-box-title-color: to the colour of the body text for the callout box.

**Review by msayoung — APPROVED** [review]

**Comment by keelanfh** [comment]
No effect on us - we use white text in call-out boxes anyway...

**Comment by markconroy** [comment]
We've had no objections to this after a week, so merging now.

**Comment by Adnan-cds** [comment]
Too late, but noticed that the fix doesn't cover h5 and h6 tags even though the [heading level field](https://github.com/localgovdrupal/localgov_paragraphs/blob/f532cf3511d5d76ea161f2e84faf0f7d74d672bf/modules/localgov_subsites_paragraphs/config/install/field.storage.paragraph.localgov_heading_level.yml#L23) provides these heading options along with h1-h4.

Also, wondering if [localgov_colour_theme](https://github.com/localgovdrupal/localgov_paragraphs/blob/2.x/modules/localgov_subsites_paragraphs/config/install/field.field.paragraph.localgov_call_out_box.localgov_colour_theme.yml) field is related to this in anyway.

**Comment by markconroy** [comment]
@Adnan-cds I left h5 and h6 out of the list as I presumed we'd never have a call out box so deep in the hierarchy. But we can easily add it in "just in case".

**Pull request merged**
