### PR TITLE
Adds a variable to let us print a token for replacement in the breadcrumb trail.

### PR DESCRIPTION
**Pull request by rupertj**
Implements #584

### CODE REVIEW

**Review by finnlewis — APPROVED** [review]
Looks good to me @markconroy and tests pass.

**Comment by markconroy** [comment]
@rupertj do we need two `{{` around the variable for ModernGov to use or just  one `{`?

**Comment by rupertj** [comment]
It'll be one in the resulting output, but we're printing the value of a variable here, so it's two.

For the purposes of making Modern.Gov work, we'll pass in {breadcrumb} as the value of the var, but if any other reverse CMS thing wants to use it (Maybe Netcall?) they can pass in what they need instead.

**Comment by markconroy** [comment]
Sounds great, let's get this merged.

**Pull request merged**
