### PR TITLE
links prev/next in guides to content instead of page

### LINKED ISSUE #416: Link guide prev/next to the guide content
At the moment when you click on prev/next for a guide, it directs to that guide page, with focus at the top of the page.

Should we link to the `lgd-guides__inner` section instead so you are brought to the next "section" of the guide rather than the next "page" of the guide?

### PR DESCRIPTION
**Pull request by markconroy**
Closes #416

### CODE REVIEW

**Comment by keelanfh** [comment]
Tested without any assistive tech and this worked fine.

However, testing with VoiceOver switched on (Chrome/Safari, macOS), when clicking on the link, VoiceOver started reading from the "Skip to main content" at the top of the page was read out, which negates the benefit for these users. Any idea why that's happening or if there's something we can do about that?

**Comment by finnlewis** [comment]
Leaving this for review.

**Review by finnlewis — COMMENTED** [review]
Tested locally and works for me in the browser. 

@keelanfh I've not tested with a voice over, are you using an extension for that or something native?

**Review by finnlewis — APPROVED** [review]

**Comment by keelanfh** [comment]
I used VoiceOver on Mac (it's native). We can just create a separate issue to have a look at that, this is still an improvement just not for people using that.

**Review by keelanfh — APPROVED** [review]

**Pull request merged**
