### PR TITLE
Prevent system messages from being cached

### LINKED ISSUE #244: Persistent status message on node page
The node add/edit feedback message becomes persistent when that node is reloaded.  This happens with the localgov_base theme and its subthemes.

## Reproduction steps
- [Optional] Install a fresh localgov site.
- Login and create a node such as a Service page.
- As expected, the status message will say *Service page PAGE-TITLE has been updated.*
- Reload the newly created node while logged in as the same user.
- The status message appears again.  Same happens following further page reloads.
- Logout and reload the above page.  There are no status messages which is good.

### PR DESCRIPTION
**Pull request by stephen-cox**
Don't check if there are messages in preprocess hook 

Fixes #244

### CODE REVIEW

**Comment by stephen-cox** [comment]
Further discussion of the implications of this change on this comment: https://github.com/localgovdrupal/localgov_base/pull/428#issuecomment-1532965127

**Comment by andybroomfield** [comment]
This is the same fix BHCC has added.

**Comment by finnlewis** [comment]
@ekes would rather wait for @markconroy to review this to confirm markup is OK.

**Review by markconroy — APPROVED** [review]
Looks good to me

**Pull request merged**
