### PR TITLE
Created template for Enquiries email field of Directory venue content type

### PR DESCRIPTION
**Pull request by bisd**
This is for Issue #496.

### CODE REVIEW

**Comment by ekes** [comment]
This probably wants just updating the field formatter default - I'll put a comment on the issue.

**Comment by bisd** [comment]
Thank you @ekes . Sorry I am not sure how to add the changed config file to this pull request. Would you please kindly advise?

**Comment by bisd** [comment]
The field formatter default has been changed with PR https://github.com/localgovdrupal/localgov_directories/pull/341

**Comment by ekes** [comment]
Fixed in https://github.com/localgovdrupal/localgov_directories/pull/341

**Pull request closed without merging**
