### PR TITLE
If the map has a value is_empty and it's true don't display.

### LINKED ISSUE #229: (Empty) map displays in directory channel
Steps to reproduce: 

1. add a directory channel
2. add promo pages
3. visit channel 
4. see an empty map

### PR DESCRIPTION
**Pull request by ekes**
The value is set for views without any location features in localgov_directories_leaflet_map_view_style_alter().

PR https://github.com/localgovdrupal/localgov_directories/pull/239
Fixes https://github.com/localgovdrupal/localgov_directories/issues/229#issuecomment-1271418506

### CODE REVIEW

**Review by markconroy — COMMENTED** [review]
This PR looks fine, but surely if the map is_empty, then we should never get as far as this template at all, or should we?

**Comment by msayoung** [comment]
> This PR looks fine, but surely if the map is_empty, then we should never get as far as this template at all, or should we?

@markconroy  see ekes' Argh here: https://github.com/localgovdrupal/localgov_directories/issues/229#issuecomment-1271418506

**Comment by markconroy** [comment]
In that case, this PR looks good to me.

**Review by markconroy — APPROVED** [review]

**Comment by finnlewis** [comment]
You want to merge and release @markconroy ?

**Pull request merged**
