### PR TITLE
Revert "sets all links to inline-block by default"

### LINKED ISSUE #423: Incorrect display of list-item markers when links are inside <li>
Setting all anchor links to inline-block display has caused the display of markers (bullet points) to appear at the bottom of multi-line list items. This might not have been the intended purpose.

Demo site - with visible marker positions

This was caused by the following commit: [changes to css \<a\> display](https://github.com/localgovdrupal/localgov_base/commit/ae8e922d91c1f8650d5813909e37429d86f9c025)

### PR DESCRIPTION
**Pull request by markconroy**
This reverts commit ae8e922d91c1f8650d5813909e37429d86f9c025.
Closes #423

### CODE REVIEW

**Review by keelanfh — CHANGES_REQUESTED** [review]
* In-text links now look fine
* Guide navigation bulletpoints now look fine
* Focus state on the news teasers on the homepage aren't correct (#396 back again) - I think those ones do need to be `inline-block`

**Comment by keelanfh** [comment]
@markconroy are you likely to have a chance to look at this and get to merge in the next couple of weeks?

No problem if not, it's just that it's currently a blocker for our launch and I need to figure out whether to ask our developers to do a fix on essex.gov.uk, or wait for LGD.

**Comment by markconroy** [comment]
Hi @keelanfh 

Sorry I was a bit longer getting to this than anticipated. Can you test again now, I've set the newsroom teasers links to inline blocks, so I think that's the last item for us. If you approve this, I'll merge it straight away and we will have it release on Monday.

**Comment by keelanfh** [comment]
No problem! We did a fix on our version anyway, it wasn't a big deal. I'll do my best to test later today.

**Comment by keelanfh** [comment]
Just tested, and the newsroom teaser focus states are fine, but the bulletpoints are off in the guide nav:

image

Is the intention to also merge #424?

**Comment by markconroy** [comment]
Yes, as soon as you OK this PR I'll merge in the other PR then. You just need to set this to "approved".

**Review by keelanfh — APPROVED** [review]

**Comment by keelanfh** [comment]
Great stuff!

**Pull request merged**
