### PR TITLE
adds CSS to allow tables to scroll on small screens

### LINKED ISSUE #579: Improve CSS on tables
@markconroy here's a card following this discussion about better mobile handling of tables

https://localgovdrupal.slack.com/archives/CSE44GLSE/p1722004702765609

### PR DESCRIPTION
**Pull request by markconroy**
Closes #579 

## What does this change?

1. Sets `.layout__region` and `.field--table` to `max-width: 100%`, so they don't overflow with any tables (or other elements)
2. Sets the .tablefield-wrapper to use `overflow-x: auto` so if it's too wide, it will have a horizonal scroll.

## How to test

1. Visit /test-subsite-demo-all-components/example-page-tables-and-tabs on a small screen and check that only the table has horizontal scroll, not the whole page.

---
Thanks to [Big Blue Door](https://www.bigbluedoor.net/) for sponsoring my time to work on this.

### CODE REVIEW

**Comment by msayoung** [comment]
@markconroy - this isn't working on Chrome and Edge, though is fine on FF. 

Not sure how but in DevTools the css is 

```
.tablefield-wrapper {
    overflow-inline: auto;
}
```
which isn't a thing.

**Comment by finnlewis** [comment]
@markconroy @msayoung : This does work for me on Chrome and Firefox, Mac. 

image

**Review by finnlewis — APPROVED** [review]
I think this works, certainly an improvement, but worth testing in other browsers perhaps?

**Comment by finnlewis** [comment]
Discussing in Merge Tuesday, we're going to merge and come back to fix things for Chrome @msayoung if neeeded.

**Pull request merged**
