### PR TITLE
Adds support for facet forms

### LINKED ISSUE #633: Front-end styling for the new Directory Facets checkbox template
We have just merged [support](https://github.com/localgovdrupal/localgov_directories/pull/399) for the [facets_form module](https://www.drupal.org/project/facets_form) into the localgov_directories module.  This has brought in a new [Twig template](https://github.com/localgovdrupal/localgov_directories/blob/3.x/templates/checkboxes--localgov-directories-facets.html.twig) into the localgov_directories module which now needs some Front-end love.  Following Andy's [suggestion](https://github.com/localgovdrupal/localgov_directories/pull/399#issuecomment-2407639169), I am raising this request here instead of the localgov_directories module.  I hope that's okay.

FOA @cjstevens78 @markconroy

### PR DESCRIPTION
**Pull request by markconroy**
Closes #633 

## What does this change?

Adds CSS so checkbox facets using facets forms look the same as default checkbox facets.

## How to test

Follow instructions [here](https://github.com/localgovdrupal/localgov_directories/pull/399) to install facets forms.

## Images

Screenshot 2024-10-15 at 11 25 54

---
Thanks to [Big Blue Door](https://www.bigbluedoor.net/) for sponsoring my time to work on this.

### CODE REVIEW

**Comment by Adnan-cds** [comment]
Hi Mark,
Many thanks for such a quick pull request.  It's nearly there.  I would request just one improvement: a bit more whitespace between the facets groups.  In the following screenshot, a little more space between the "South (1)" facet item and the "Size" facet group label would be great:
image

**Comment by markconroy** [comment]
@Adnan-cds can you check again?

**Comment by Adnan-cds** [comment]
Thanks, this will do:
image

**Review by Adnan-cds — APPROVED** [review]
Works for me.  Thanks a lot :)

**Pull request merged**
