### PR TITLE
332 header js does not ensure operations happen only once unnecessary reassignment of context

### PR DESCRIPTION
**Pull request by ctorgalson**
This PR's main intention is to address the issues raised in #332, but I've used that as an excuse for streamlining and regularizing the code--but without substantially altering the logic.

Reproducing the commit message from f78af4e, here's a list of the basic changes:

  - trailing whitespace trimmed,
  - whitespace in general attended to,
  - remove a LOT of unnecessary querySelector() calls,
  - consolidate most-used DOM references in navInfo variable,
  - regularize ternaries (there were three or more styles in use),
  - eliminate several element.classList .contains() / .add() / .remove()
    ternaries via the use of element.classList.toggle(),
  - collect variables declarations/assignments at the beginning of the file,
  - separate the header search label manipulation from the nav/button work,
  - use variables instead of repeating class names and selectors,

As far as I can see, I haven't broken anything :grimacing: 

Incidentally, for reviewers, I didn't mention this specifically in commit messages, but I've changed all instances of this structure:

```js
      let foo;
      let bar;
      if (context.querySelector('.foo')) {
        foo = context.querySelector('.foo');
      }
      if (context.querySelector('.bar')) {
        bar = context.querySelector('.bar');
      }
```

...to this structure:

```js
  const foo = context.querySelector('.foo');
  const bar = context.querySelector('.bar');
```

...because:

  - it's shorter,
  - these variables are never redefined (i.e. `const`, not `let`),
  - it's more efficient (half the `querySelector()` calls),
  - the result if the DOM element is missing is similar (now the result will be ~empty `NodeList` objects~ `null` instead of `undefined` ~variables~)

### CODE REVIEW

**Comment by finnlewis** [comment]
Leaving this one for @markconroy and @msayoung to test.

**Comment by ekes** [comment]
Just logging my comments: once makes complete sense; and code looks much nicer. I'm not sure if there are automated tests for this? So I think it certainly needs one other person doing and install and manually confirming no issues.

**Comment by finnlewis** [comment]
Thanks @ekes 

Let's let @markconroy  and / or @msayoung test this and approve.

**Comment by markconroy** [comment]
This looks good to me, tested it on the site I am currently working on.

**Pull request merged**
