### PR TITLE
sets colour for title on death of person alert

### LINKED ISSUE #310: Title colour for death of a notable person alert banner
Currently the title is black on a black background.

### PR DESCRIPTION
**Pull request by markconroy**
Closes #310

### CODE REVIEW

**Comment by andybroomfield** [comment]
I'd be happy with this, however see [my comment](https://github.com/localgovdrupal/localgov_alert_banner/pull/225#discussion_r1003475205) as I think there is a better solution.

````css
.localgov-alert-banner .localgov-alert-banner__title {
  color: inherit;
}
````

**Comment by markconroy** [comment]
@andybroomfield `inherit` is fine, but means you need to add specific CSS to override it in your sub-theme. I think that's appropriate for the CSS in your module, but in the base theme we are trying to make things override-able via a CSS variable. So in this case, to change the color of that title, you just need to reset what that variable is in your `variables.css` file.

**Comment by andybroomfield** [comment]
@markconroy fair enough, just an FYI, the bug exists for all the alert banner kinds, not just notable person. Its just we don't notice it since we set the colour of the text to black on those banners. The h2 colour is currently setting it so they will change if someone changes the h2 colour.

Screenshot 2022-10-25 at 9 29 58 am

**Comment by markconroy** [comment]
PR updated, so we can cover each banner type.

**Review by andybroomfield — APPROVED** [review]
This works great now, thanks @markconroy

**Pull request merged**
