### PR TITLE
335 Fix focus state text wrapping issue

### LINKED ISSUE #335: Focus indicator does not appear correctly on <a> elements wrapping on multiple lines in Chrome, Edge
Examples:

image
image
image

I think this is a WCAG 2.1 AA fail because without the underline, the focus indicator does not have sufficient contrast against white backgrounds.

Correct behaviour (working in Safari):

image

### PR DESCRIPTION
**Pull request by keelanfh**
To fix #335 

Just tested in the browser inspector (I copied this change from GOV.UK and it appears to work), I didn't build and test a site. Would be great if someone could test in Chrome and Edge as those are the browsers where I observed this issue.

### CODE REVIEW

**Comment by keelanfh** [comment]
On further investigation, this issue came up due to a change in Chromium 108.

See issue on GOV.UK Frontend which describes this and the change they made: https://github.com/alphagov/govuk-frontend/pull/3107

Chrome requires the vendor-prefixed `-webkit-box-decoration-break` rather than `box-decoration-break` - I assume this is added later by the GOV.UK Frontend tech stack

**Comment by keelanfh** [comment]
Applied the patch to a fresh install, and it looks OK with the demo content.

**Comment by finnlewis** [comment]
Thanks @keelanfh !

We can review at Merge Monday meeting at 2pm today, unless anyone has a change to take a look sooner.

**Review by finnlewis — APPROVED** [review]
@markconroy approves this!

**Pull request merged**
