### PR TITLE
adds styling for the preview link feature

### LINKED ISSUE #343: Layout on "Preview Link" share page
When you go to "Preview Link", the page with the link to share looks a bit odd. For guide pages, the buttons also come right up against the previous/next navigation buttons.

image

### PR DESCRIPTION
**Pull request by markconroy**
Closes #343

### CODE REVIEW

**Comment by finnlewis** [comment]
Before: 
image

After: 
image

Definitely an improvement..

**Comment by finnlewis** [comment]
image

Better still! Thanks @markconroy

**Review by finnlewis — APPROVED** [review]
Looks good to me! Thanks @markconroy

**Comment by keelanfh** [comment]
Tested and LGTM, thanks for this! 👍

**Review by keelanfh — APPROVED** [review]

**Comment by finnlewis** [comment]
@markconroy is busy today, but keen for a release, so merging this to prep a release pull request.

**Pull request merged**
