### PR TITLE
Set default colours for subsites extras

### LINKED ISSUE #550: Set subsite menu colors to dark with light text
As many councils don't have dev help immediately to hand, we need the menu provided by subsite extras to be as useable as possible out of the box

This is what the menu currently looks like, which can't be used out of the box

Image

We need to set as default:

- the menu background color to dark
- the text color to light

This seems to be the pattern used by most councils I've seen

We can provide controls for councils to set these colors at a later date

### PR DESCRIPTION
**Pull request by markconroy**
Closes #550

Default is now:

1. Background colour of region: accent
2. Background colour of menu items: white
3. Colour of menu items text: accent
4. Border on menu items: white

(Basically, the opposite of what we had.)

Screenshot 2024-05-29 at 15 30 47

===
Thanks to [Big Blue Door](https://www.bigbluedoor.net/) for sponsoring my time to work on this.

### CODE REVIEW

**Comment by willguv** [comment]
Can you add a screenshot please @markconroy cheers. Thanks for looking at this so quickly

**Comment by markconroy** [comment]
@willguv screenshot added above just now

**Comment by finnlewis** [comment]
@willguv would like to discuss the menu items looking like buttons. Potentially want a slightly different approach for subsites extras menus.

**Comment by willguv** [comment]
@markconroy is it easy to make it look like this out of the box?

https://new.dumgal.gov.uk/gretna-registration-office/your-wedding-ceremony

Screenshot 2024-06-11 at 12 32 21

Screenshot 2024-06-11 at 12 32 28

**Review by msayoung — APPROVED** [review]

**Comment by markconroy** [comment]
@willguv Some updates:

1. Default state - no background colour on menu links
2. Hover state - white background, with link underlined
3. Active trail state - white background, no underline, menu tab merges with white section of page below it

All the variables we created are still there so easy to have any style you want, and some new variables have been created to make this even more flexible.

Default:

Screenshot 2024-06-14 at 09 47 08


Hover:

Screenshot 2024-06-14 at 09 47 20


Active:

Screenshot 2024-06-14 at 09 47 29

**Comment by willguv** [comment]
That's spot on, thanks @markconroy!

**Pull request merged**
