### PR TITLE
Stopped form and input tags being stripped out when determining if a region is empty or not.

### PR DESCRIPTION
**Pull request by rupertj**
Fixes issue #234

### CODE REVIEW

**Comment by markconroy** [comment]
HI @rupertj 

Does your form have no content at all? As in, is there not even text on a submit button or inside a label that would cause our check to validate?

**Comment by rupertj** [comment]
It's an exposed form from views being used as a search form, so there's a placeholder in a single field, and then a button to submit it.

Here's the markup if you're curious:

```
<div class="views-exposed-form block block-lbhf-search block-lbhf-sitewide-search-block" data-drupal-selector="views-exposed-form-search-default" id="block-lbhfsitewidesearchblock">
    <form action="/search" method="get" id="views-exposed-form-search-default-block" accept-charset="UTF-8">
        <div class="js-form-item form-item js-form-type-search-api-autocomplete form-item-s js-form-item-s form-no-label">
            <input data-drupal-selector="edit-s" placeholder="Search" type="text" id="edit-s" name="s" value="" size="30" maxlength="128" class="form-text required" required="required" aria-required="true">
        </div>
        <div data-drupal-selector="edit-actions" class="form-actions js-form-wrapper form-wrapper" id="edit-actions">
            <input data-drupal-selector="edit-submit-search" type="submit" id="edit-submit-search" value="Apply" class="button js-form-submit form-submit">
        </div>
    </form>
</div>
```

Having thought about it a bit more, there's other scenarios that could also fail, like a linked image in a block.

**Comment by rupertj** [comment]
I was just reading the d.o issue linked in the code, and found the last comment interesting: https://www.drupal.org/project/drupal/issues/953034#comment-14588869 . The contrib module linked there uses this set of tags as ones that should remain when determining if a region is empty or not:
```
[
    '<drupal-render-placeholder>',
    '<embed>',
    '<hr>',
    '<iframe>',
    '<img>',
    '<input>',
    '<link>',
    '<object>',
    '<script>',
    '<source>',
    '<style>',
    '<video>',
];
```

**Comment by markconroy** [comment]
Looks good. Thanks @rupertj

**Pull request merged**
